name: üöÄ Deploy to VPS

on:
  push:
    branches:
      - master # O main, seg√∫n tu rama principal

jobs:
  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-latest

    steps:
      - name: üìÇ Checkout repo
        uses: actions/checkout@v3

      - name: Verificar clave SSH
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa  # Verifica que la clave se haya cargado correctamente
          ls -la ~/.ssh  # Verifica los permisos de la clave SSH

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH connection works'"


      - name: üîê Connect & Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd travel_agency
            git pull origin master
            npm install
            npm run build
            pm2 restart travel_agency
